### ISSUE TITLE
Merge latest golang/src/x509 and .../asn1 into our forks.

### ISSUE THREAD

**Issue by AlCutter** [google/certificate-transparency#1008]
The world has continued to spin since we forked the `x509` and `asn1` packages, we should probably merge in updates from the newer versions.

**Comment by benlaurie** [comment]
Is there no chance of getting them to take our patches?

**Comment by pphaneuf** [comment]
Don't we know some of the authors? :wink:

**Comment by benlaurie** [comment]
We do, but that didn't help.

Is anyone planning to do this? I am hitting various bugs in x509...
