### ISSUE TITLE
xjson-server: No change to tree_size

### ISSUE THREAD

**Issue by AndrewGorton** [google/certificate-transparency#1082]
Following on from ct-clustertool.

I have set up the ETCD cluster and run ct-clustertool successfully.

I now start xjson-server on separate two nodes (same ct.key file, no shared storage) with

```
xjson-server \
        --port=8080 \
        --tree_signing_frequency_seconds=30 \
        --guard_window_seconds=10 \
        --leveldb_db=/data/log.ldb \
        --etcd_servers="$ETCD_ALL" \
        --etcd_delete_concurrency=100 \
        --num_http_server_threads=32 \
        --key=ct.key &
```
I can view the contents via

```
$ curl localhost/ct/v1/get-sth
{ "tree_size": 0, "timestamp": 1450367774773, "sha256_root_hash": "47DEQpj8HBSa+\/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=", "tree_head_signature": "BAMARjBEAiA5TWEVw1ptS29iksZAYX0TFzDpKPRRNzZnfAyay0G4HwIgQGKgrB9\/aDDe2Y4Bd4KkRbCYuDzj7CoOpPGtdZyv3NM=" }
```

I then try to add to the tree with

```
$ curl -X POST -d '{}' localhost/ct/v1/add-json
{ "sct_version": 0, "id": "2eaEklYkbiZLDw9zNMFskl+b\/bvg0G8BDRZct3X7YlY=", "timestamp": 1450367493881, "extensions": "", "signature": "BAMARzBFAiB\/wnUAeJkHIbhKdYQ3Fs4XzxeBuEkGNqykYtsr+9RT5AIhALd1W7uscwjjfUtyNsmiKwckP2tPltDM3v0xIRc9aWKu" }
```

I wait for several minutes before checking it got added with:-

```
 $ curl localhost/ct/v1/get-sth
{ "tree_size": 0, "timestamp": 1450368344796, "sha256_root_hash": "47DEQpj8HBSa+\/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=", "tree_head_signature": "BAMARzBFAiEAlTqTgX3xhMMevxPFBff2CvDkiCyjy5PMupuUnqpGDCUCIFgypSEXoyqQvS9ab2P6XuqeBoC8h7yVHSvLqvQLd+df" }
```
but the tree_size hasn't increased.

The 2nd instance of xjson-server is reporting lots of 

```
I1217 15:59:57.300621    23 fetcher.cc:227] error fetching entries at index 0: UNKNOWN: 
```

in /tmp/xjson-server.INFO

Any thoughts appreciated! (We've got it working in -i_know_stand_alone_mode_can_lose_data mode).

Cheers,

A.

**Comment by AlCutter** [comment]
#1088 should've addressed this, so I'll close it for now - any more problems feel free to reopen!

**Comment by AndrewGorton** [comment]
@AlCutter Your changes seem to have fixed things as I can now run xjson-server in a 3-node cluster. Many thanks for your help!

**Comment by AndrewGorton** [comment]
Might have spoken too soon!

```
W0120 09:54:21.686851    18 server.cc:209] Waiting for local database to catch up to serving_sth (0 of 804)
I0120 09:54:21.686983    20 fetcher.cc:227] error fetching entries at index 0: UNKNOWN: 
```

but this may be because the Nix package binaries aren't up to date.

**Comment by philandstuff** [comment]
I had a spare 10 minutes so I created NixOS/nixpkgs#12497 to bump the nix package.

**Comment by AndrewGorton** [comment]
@philandstuff There was a build a day ago via Hydra so I've rebuilt the Docker image to see if it picks it up.

**Comment by philandstuff** [comment]
@AndrewGorton yeah but the nix expression was pinned to a particular commit (ie 250672b5aef3666edbdfc9a75b95a09e7a57ed08) so the hydra build will have built an old version of certificate-transparency.

**Comment by AlCutter** [comment]
BTW, somewhere up near the top of the info log from the server should be a line telling you the commit hash from which the server was built:
```
I0120 12:36:22.581251 25026 init.cc:71] Build version: a2d5140d9ba60f1657b4483e4f603fd636b7d94b-dirty
```
So in theory you should be able to work out what's gone in.
(BTW the `-dirty` tag just shows I've fiddled with my local branch)

**Comment by AndrewGorton** [comment]
@philandstuff Ah. Much obliged - when it completes, I'll rebuild the Docker image. How will I know when it finishes? (I see there's a Travis job, but thought it was built via Hyda?)
