### ISSUE TITLE
Some tools do not work with logs that use RSA keys

### ISSUE THREAD

**Issue by RJPercival** [google/certificate-transparency#1092]
The following scripts are hard-coded to expect ECDSA log keys:
- python/ct/crypto/tools/verify_util.py
- python/utilities/submit_chain/submit_chain.py

They crash if either given an RSA log key or pointed at a log_list.json file that contains an RSA key (e.g. https://www.certificate-transparency.org/known-logs/log_list.json - the Venafi log key).

**Comment by RJPercival** [comment]
Fixed by #1111 and #1116.

**Comment by RJPercival** [comment]
I've found another script that is hard-coded for ECDSA:

- python/utilities/dnslookup/dnslookup.py

**Comment by benlaurie** [comment]
Yeah ... we might have trouble with RSA keys, it occurs to me (response size might be too large to fit in a TXT record). We should test that.

**Comment by RJPercival** [comment]
It looks like dnslookup.py was fixed by https://github.com/google/certificate-transparency/commit/097b6c6de12bd103aae810b21dbdc20daddded84, thanks @benlaurie.
