### ISSUE TITLE
LogObserver has problem ingesting certs with 'ASN1Error: Corrupt time'

### ISSUE THREAD

**Issue by phad** [google/certificate-transparency#1108]
This has been seen with two certificates logged today (2016-02-08) to Pilot and Certly.io:

https://crt.sh/?id=12716424   [Pilot: 12588941,  Certly.io:  721444]
and
https://crt.sh/?id=906173   [Pilot:  12595432, Certly.io: 720002]

Both certificates were issued by: 
L=ValiCert Validation Network/O=ValiCert, Inc./OU=ValiCert Class 2 Policy Validation Authority/CN=http://www.valicert.com//emailAddress=info@valicert.com

Python traceback:
E0208 15:27:07.660867    1005 reporter.py:93] Error scanning certificate 12595432 in batch <12595432, 12595432> - it will be excluded from the scan results
Traceback (most recent call last):
  File "certificate_transparency/python/ct/client/reporter.py", line 52, in _scan_der_cert
    partial_result += check.check(certificate) or []
  File "certificate_transparency/python/ct/cert_analysis/validity.py", line 47, in check
    not_before = certificate.not_before()
  File "certificate_transparency/python/ct/crypto/cert.py", line 543, in not_before
    return (self._asn1_cert["tbsCertificate"]["validity"]["notBefore"].
  File "certificate_transparency/python/ct/crypto/asn1/x509_time.py", line 33, in gmtime
    raise error.ASN1Error("Corrupt time: %s" % self._value)
ASN1Error: Corrupt time: 040629100620

**Comment by benlaurie** [comment]
This is because the time should have a trailing Z but OpenSSL unfortunately
accepts time missing that.

**Comment by eranmes** [comment]
Should be fixed by https://github.com/google/certificate-transparency/commit/87fae561b0e1b8525075c30fbaf1217cfd803a07, right?
