### ISSUE TITLE
Cannot compile: fatal error

### ISSUE THREAD

**Issue by stas730** [google/certificate-transparency#1203]
Clang version: 3.4-1ubuntu3
Error:
```
src/tmalloc.cc:110:10: fatal error: 'algorithm' file not found
```
File:
```
#include <algorithm>    many spaces  // for max, min
```
How to fix it?

**Comment by stas730** [comment]
After gclient sync.

**Comment by stas730** [comment]
After two -Wnoerrors in README, this error not fixes. How to add 'algorithm' to clang?

**Comment by pphaneuf** [comment]
`algorithm` is a standard C++ header, so if it's not there, it sounds like you're missing the C++ standard library, maybe? On Ubuntu, it would be provided by one of the packages providing `libstdc++-dev`. It's also possible, since you're using Clang, that you have the G++ library, and you need the other one (`libc++-dev`, I believe?).

Note also that we test with Clang 3.6, which is newer than the one you mentioned.

**Comment by stas730** [comment]
I will try tomorrow.

**Comment by stas730** [comment]
I installed this two packages — I see error again.

**Comment by stas730** [comment]
I detected mistake in first message.
#include <algorithm>

**Comment by stas730** [comment]
It is Markdown…

**Comment by pphaneuf** [comment]
I edited your comments to use the Markdown multiline no-formatting quoting, this should help!

This is just one line of code, that we use in several files, so there's no error with that line. Do you have any of those files installed on your system?

```bash
$ ls -l /usr/include/c++/*/algorithm 
-rw-r--r-- 1 root root   2528 Mar 20  2014 /usr/include/c++/4.4.7/algorithm
-rw-r--r-- 1 root root   2528 Mar 20  2014 /usr/include/c++/4.4/algorithm
-rw-r--r-- 1 root root   2564 Mar 20  2014 /usr/include/c++/4.6.4/algorithm
-rw-r--r-- 1 root root   2564 Mar 20  2014 /usr/include/c++/4.6/algorithm
-rw-r--r-- 1 root root   2518 Jan 27 06:30 /usr/include/c++/4.8.4/algorithm
-rw-r--r-- 1 root root   2518 Jan 27 06:30 /usr/include/c++/4.8/algorithm
-rw-r--r-- 1 root root 196825 Jan 19  2014 /usr/include/c++/v1/algorithm
```

Could you provide more of the build output? Say, the last 20 lines or so?

**Comment by benlaurie** [comment]
Clang version 3.4 is pretty ancient. Suggest you upgrade to something more recent.

**Comment by stas730** [comment]
V1, 4.8 and 4.8.4 (link to 4.8).

**Comment by pphaneuf** [comment]
So you have the file, but it's not being found by your compiler, somehow.

We do test more frequently with Clang 3.6, as I mentioned earlier, but I do use Clang 3.4 on my own workstation, and I'm able to build successfully:

```
$ clang++ --version
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

**Comment by stas730** [comment]
I upgrading to Clang 3.6…

**Comment by stas730** [comment]
Fix the README!
export CXX=clang++-3.6 CC=clang-3.6 (for 3.6)

**Comment by stas730** [comment]
Compiling again… with aliases.

**Comment by stas730** [comment]
Not working.

**Comment by stas730** [comment]
How to fix "command not found"? My clang++ is clang++-3.6

**Comment by stas730** [comment]
AGAIN? Algorithm not found.

**Comment by stas730** [comment]
What flags used to compile it?

**Comment by stas730** [comment]
UPD:
I think -stdlib=libc++
But how to use it with gclient sync?
CXXFLAGS aren't working.

**Comment by stas730** [comment]
I will try to compile with GCC or use CXX=clang++-3.6 -stdlib=libc++
If this methods will not work I will create my root DNS and make fake sync.

**Comment by pphaneuf** [comment]
Compiling with GCC should work too. You can see the exact commands that our automated build system (which runs on Ubuntu) uses in this file:

https://github.com/google/certificate-transparency/blob/master/.travis.yml#L97

Higher up in that file you can find packages and PPAs that we added:

https://github.com/google/certificate-transparency/blob/master/.travis.yml#L13

**Comment by pphaneuf** [comment]
It would be a lot easier to help you if you provided more of the build output (the last 20 or 30 lines, say?).

**Comment by stas730** [comment]
I forgot 20 lines. I know only last two (GCC):
checking for namespace support... no configure: error: Namespace support is required to build ICU.

**Comment by pphaneuf** [comment]
It's as if you had some other *really old*, not really working C++ compiler that was used?

**Comment by stas730** [comment]
GCC 4.8.4-2ubuntu1~14.04.1

**Comment by stas730** [comment]
Or how to pass "algorithm" with Clang?
I need libc++ as default to compile with Clang.

**Comment by stas730** [comment]
How to use libc++ as default libstd?

**Comment by stas730** [comment]
CXX=clang++ -stdlib=libc++
Ok. I fixed it.
Next error is fixed by linking libstdc++.so.6 to libstdc++.so (I forgot file name).
Next error:
./.libs/libtcmalloc_minimal.a(libtcmalloc_minimal_la-tcmalloc.o): In function `std::__1::__vector_base_common<true>::__throw_length_error() const':
src/tcmalloc.cc:(.text._ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv[_ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv]+0x50): undefined reference to `std::logic_error::logic_error(char const*)'
./.libs/libtcmalloc_minimal.a(libtcmalloc_minimal_la-tcmalloc.o): In function `std::__1::__basic_string_common<true>::__throw_length_error() const':
src/tcmalloc.cc:(.text._ZNKSt3__121__basic_string_commonILb1EE20__throw_length_errorEv[_ZNKSt3__121__basic_string_commonILb1EE20__throw_length_errorEv]+0x50): undefined reference to `std::logic_error::logic_error(char const*)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [malloc_extension_c_test] Error 1
make[2]: Leaving directory `/home/myuser/apache2/ct/tcmalloc'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/myuser/apache2/ct/tcmalloc'
make: *** [_tcmalloc] Error 2
Error: Command 'make -f /home/myuser/apache2/ct/certificate-transparency/build.gclient _tcmalloc' returned non-zero exit status 2 in /home/myuser/apache2/ct
Hook 'make -f /home/myuser/apache2/ct/certificate-transparency/build.gclient _tcmalloc' took 13.40 secs

P. S. myuser is not real username.

**Comment by stas730** [comment]
Apache2 is not an Apache dir.

**Comment by stas730** [comment]
*directory

**Comment by pphaneuf** [comment]
OK, now we're getting somewhere with this! So it found the "algorithm" header, but from the linking error you gave, I think you're getting the wrong libstdc++.so, which doesn't match with the headers it found?

Normally, the symlinks are made with `sudo ldconfig` (which is normally run by `apt-get`/`dpkg` on Ubuntu), so maybe you made the wrong symlink? You could try running `sudo ldconfig`, to let it fix it?

Make should have the linking command a bit before, I think *both* the `CXX` and the `LDFLAGS` might need to have `-stdlib=libc++` in it, so that they both "agree" on the right library to use?

**Comment by stas730** [comment]
myuser@mypc $ sudo ldconfig
myuser@mypc $ export LDFLAGS="-lc++" # Because I cannot run ld -libstd=libc++
myuser@mypc $ gclient sync
# Very long log
# This error again
myuser@mypc $ echo ":("
:(

**Comment by stas730** [comment]
Markdown big text is only comment with spaces after #.

**Comment by stas730** [comment]
Waiting for reply…

**Comment by pphaneuf** [comment]
We would need more of the output just before, so that the `clang++` command is included. For example, I think this is the matching output from https://travis-ci.org/google/certificate-transparency/jobs/132305389:

```
/bin/bash ./libtool --tag=CC   --mode=link clang-3.6 -pthread  -ansi -fPIC -pthread  -L/home/travis/build/google/certificate-transparency/../install/lib  -o malloc_extension_c_test src/tests/malloc_extension_c_test-malloc_extension_c_test.o libtcmalloc_minimal.la -lpthread -lstdc++ -lm
libtool: link: clang-3.6 -pthread -ansi -fPIC -pthread -o malloc_extension_c_test src/tests/malloc_extension_c_test-malloc_extension_c_test.o  -L/home/travis/build/google/certificate-transparency/../install/lib ./.libs/libtcmalloc_minimal.a -lpthread -lstdc++ -lm -pthread
clang: warning: argument unused during compilation: '-ansi'
```

**Comment by stas730** [comment]
myuser@mypc:~/apache2/ct$ libtool --tag=CC   --mode=link clang-3.6 -pthread  -ansi -fPIC -pthread  -L/home/myuser/apache2/ct/install/lib  -o malloc_extension_c_test /home/myuser/apache2/ct/tcmalloc/src/tests/malloc_extension_c_test-malloc_extension_c_test.o /home/myuser/apache2/ct/tcmalloc/libtcmalloc_minimal.la -lpthread -lstdc++ -lm
libtool: link: clang-3.6 -pthread -ansi -fPIC -pthread -o malloc_extension_c_test /home/myuser/apache2/ct/tcmalloc/src/tests/malloc_extension_c_test-malloc_extension_c_test.o  -L/home/myuser/apache2/ct/install/lib /home/myuser/apache2/ct/tcmalloc/.libs/libtcmalloc_minimal.a -lpthread -lstdc++ -lm -pthread
clang: warning: argument unused during compilation: '-ansi'
/home/myuser/apache2/ct/tcmalloc/.libs/libtcmalloc_minimal.a(libtcmalloc_minimal_la-tcmalloc.o): In function `(anonymous namespace)::cpp_alloc(unsigned int, bool)':
src/tcmalloc.cc:(.text+0xb06): undefined reference to `std::bad_alloc::bad_alloc()'
/home/myuser/apache2/ct/tcmalloc/.libs/libtcmalloc_minimal.a(libtcmalloc_minimal_la-tcmalloc.o): In function `std::__1::__vector_base_common<true>::__throw_length_error() const':
src/tcmalloc.cc:(.text._ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv[_ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv]+0x50): undefined reference to `std::logic_error::logic_error(char const*)'
/home/myuser/apache2/ct/tcmalloc/.libs/libtcmalloc_minimal.a(libtcmalloc_minimal_la-tcmalloc.o): In function `std::__1::__basic_string_common<true>::__throw_length_error() const':
src/tcmalloc.cc:(.text._ZNKSt3__121__basic_string_commonILb1EE20__throw_length_errorEv[_ZNKSt3__121__basic_string_commonILb1EE20__throw_length_errorEv]+0x50): undefined reference to `std::logic_error::logic_error(char const*)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
myuser@mypc:~/apache2/ct$

**Comment by stas730** [comment]
Fixed:
`myuser@mypc:~/apache2/ct$ libtool --tag=CC   --mode=link clang-3.6 -pthread  -ansi -fPIC -pthread  -L/home/myuser/apache2/ct/install/lib  -o malloc_extension_c_test /home/myuser/apache2/ct/tcmalloc/src/tests/malloc_extension_c_test-malloc_extension_c_test.o /home/myuser/apache2/ct/tcmalloc/libtcmalloc_minimal.la -lpthread -lstdc++ -lm
libtool: link: clang-3.6 -pthread -ansi -fPIC -pthread -o malloc_extension_c_test /home/myuser/apache2/ct/tcmalloc/src/tests/malloc_extension_c_test-malloc_extension_c_test.o  -L/home/myuser/apache2/ct/install/lib /home/myuser/apache2/ct/tcmalloc/.libs/libtcmalloc_minimal.a -lpthread -lstdc++ -lm -pthread
clang: warning: argument unused during compilation: '-ansi'
/home/myuser/apache2/ct/tcmalloc/.libs/libtcmalloc_minimal.a(libtcmalloc_minimal_la-tcmalloc.o): In function `(anonymous namespace)::cpp_alloc(unsigned int, bool)':
src/tcmalloc.cc:(.text+0xb06): undefined reference to `std::bad_alloc::bad_alloc()'
/home/myuser/apache2/ct/tcmalloc/.libs/libtcmalloc_minimal.a(libtcmalloc_minimal_la-tcmalloc.o): In function `std::__1::__vector_base_common<true>::__throw_length_error() const':
src/tcmalloc.cc:(.text._ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv[_ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv]+0x50): undefined reference to `std::logic_error::logic_error(char const*)'
/home/myuser/apache2/ct/tcmalloc/.libs/libtcmalloc_minimal.a(libtcmalloc_minimal_la-tcmalloc.o): In function `std::__1::__basic_string_common<true>::__throw_length_error() const':
src/tcmalloc.cc:(.text._ZNKSt3__121__basic_string_commonILb1EE20__throw_length_errorEv[_ZNKSt3__121__basic_string_commonILb1EE20__throw_length_errorEv]+0x50): undefined reference to `std::logic_error::logic_error(char const*)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
myuser@mypc:~/apache2/ct$ `

**Comment by stas730** [comment]
Not all code is marked as code. :(

**Comment by stas730** [comment]
With lc++ it compiles.
And test response: PASS

**Comment by pphaneuf** [comment]
Hmm, so the problem here is that tcmalloc tries to manually link (in "C mode") to the C++ standard library, but while it's been built using libc++, the linking step uses libstdc++, which doesn't work correctly (as the errors say).

I'm looking at my own system (also Ubuntu-based), as well as the automated build, and it appears that while we can build with both Clang and GCC, everything I see uses libstdc++, *not* libc++.

So maybe you found a bug in the build system?

I see you had some `-stdlib=libc++` flags, could you try with `-stdlib=libstdc++`? You might need to delete the build directory, otherwise it might not take effect properly.

**Comment by stas730** [comment]
`#include <algorithm>`

**Comment by stas730** [comment]
Trying to compile with libc++ again…

**Comment by pphaneuf** [comment]
If it gets the error for `#include <algorithm>`, you might be missing the `libstdc++-4.8-dev` package.

**Comment by pphaneuf** [comment]
(or maybe a slightly different version, like `libstdc++-4.9-dev`, depending on what you already have on your system?)

**Comment by stas730** [comment]
GCC 4.9 not available in my system

**Comment by stas730** [comment]
I fixed it! No fake sync, just modify file after sync.

**Comment by stas730** [comment]
Waiting for end. Or for error.

**Comment by stas730** [comment]
No errors…
I waiting…

**Comment by stas730** [comment]
make -C certificate-transpa

**Comment by stas730** [comment]
Errors with make!
I do make clean, but errors shows again.
`cpp/net/connection_pool.cc:213:5: error: unused typedef
'INVALID_REQUESTED_LOG_SEVERITY' [-Werror, -Wunused-local-typedef]
LOG_EVERY_N(WARNING, 100)
^
/home/myuser/apache2/ct/install/include/glog/logging.h:917:30: note:
expanded from macro 'LOG_EVERY_N'
INVALID_REQUESTED_LOG_SEVERITY); //many spaces \
^
/home/myuser/apache2/ct/install/include/glog/logging.h:912:73: note:
expanded from macro 'GOOGLE_GLOG_COMPILE_ASSERT'
typedef google::glog_internal_namespace_::CompileAssert<(bool(expr))> ms...
^`
Sorry for missing spaces.

**Comment by pphaneuf** [comment]
Ah, now we're into territory where we understand better!

There is a few problems with some newer versions of Clang that we detect and disable:

https://github.com/google/certificate-transparency/blob/master/build/configure-ct#L25

But it seems like the detection does not work correctly?

What is the `CXX` environment variable set to? If you set it to start with `clang++` (no version), maybe change it to have `clang++-3.6` (I think that's the version you have) instead?

You should *not* need to do a clean, this will not change the generated result, only the error messages.

**Comment by stas730** [comment]
I removed /usr/bin/clang & /usr/bin/clang++
I created it for "fix" some days ago.

**Comment by stas730** [comment]
Syncing again…
But I need to save more than one change…

**Comment by stas730** [comment]
How to fix "-lstdc++" in gclient sync?
Fake root DNS, sync?
Please, remove libstdc++ from tcmalloc. And set libc++ as default.

**Comment by pphaneuf** [comment]
We build this software multiple times per hour on Ubuntu, using Clang, so I'm almost certain that there is some problem with your particular installation?

For example, you can see all the commands needed to build from a clean Ubuntu system here (note the little triangles of the left side, some commands are collapsed and can be expanded by clicking on the triangles):

https://travis-ci.org/google/certificate-transparency/jobs/132856314

I don't understand what you mean by "fake root DNS"?

**Comment by stas730** [comment]
Fake root DNS is root DNS server installed on 127.0.0.1 (localhost). And it redirects from github.com to fake git repository.
`In file included from cpp/server/server.cc:1:
In file included from ./cpp/server/server.h:5:
In file included from /usr/include/c++/v1/memory:593:
/usr/include/c++/v1/type_traits:433:83: error: no matching function for call to
      '__source'
  ...__libcpp_is_function_imp::__source<_Tp>())) == 1>
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/type_traits:438:14: note: in instantiation of template class
      'std::__1::__libcpp_is_function<std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> > () const, false>' requested
      here
    : public __libcpp_is_function<_Tp> {};
             ^
/usr/include/c++/v1/type_traits:443:97: note: in instantiation of template class
      'std::__1::is_function<std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> > () const>' requested here
  ...struct __libcpp_is_member_function_pointer<_Tp _Up::*> : public is_funct...
                                                                     ^
/usr/include/c++/v1/type_traits:446:14: note: in instantiation of template class
      'std::__1::__libcpp_is_member_function_pointer<std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> >
      (cert_trans::ClusterStateController::*)() const>' requested here
    : public __libcpp_is_member_function_pointer<typename remove_cv<_Tp>...
             ^
/usr/include/c++/v1/type_traits:460:38: note: in instantiation of template class
      'std::__1::is_member_function_pointer<std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> >
      (cert_trans::ClusterStateController::*)() const>' requested here
                                    !is_member_function_pointer<_Tp>::value> {};
                                     ^
/usr/include/c++/v1/type_traits:3122:17: note: in instantiation of template
      class
      'std::__1::is_member_object_pointer<std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> >
      (cert_trans::ClusterStateController::*)() const>' requested here
                is_member_object_pointer<typename remove_reference<_Fp>:...
                ^
/usr/include/c++/v1/type_traits:3129:1: note: (skipping 7 contexts in backtrace;
      use -ftemplate-backtrace-limit=0 to see all)
__invoke(_Fp&& __f, _A0&& __a0)
^
/usr/include/c++/v1/type_traits:3147:13: note: while substituting deduced
      template arguments into function template '__invoke' [with _Fp =
      std::__1::__bind<std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> >
      (cert_trans::ClusterStateController::*)() const,
      cert_trans::ClusterStateController *> &, _Args = <>]
            __invoke(_VSTD::declval<_Fp>(), _VSTD::declval<_Args>()...)
            ^
/usr/include/c++/v1/type_traits:3155:11: note: in instantiation of template
      class
      'std::__1::__invokable_imp<std::__1::__bind<std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> >
      (cert_trans::ClusterStateController::*)() const,
      cert_trans::ClusterStateController *> &>' requested here
          __invokable_imp<_Fp, _Args...>::value>
          ^
/usr/include/c++/v1/functional:1427:33: note: in instantiation of template class
      'std::__1::__invokable<std::__1::__bind<std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> >
      (cert_trans::ClusterStateController::*)() const,
      cert_trans::ClusterStateController *> &>' requested here
                                __invokable<_Fp&, _ArgTypes...>::value>
                                ^
/usr/include/c++/v1/functional:1454:41: note: in instantiation of default
      argument for
      '__callable<std::__1::__bind<std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> >
      (cert_trans::ClusterStateController::*)() const,
      cert_trans::ClusterStateController *> >' required here
                                        __callable<_Fp>::value &&
                                        ^~~~~~~~~~~~~~~
cpp/server/server.cc:249:26: note: while substituting deduced template arguments
      into function template 'function' [with _Fp =
      std::__1::__bind<std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> >
      (cert_trans::ClusterStateController::*)() const,
      cert_trans::ClusterStateController *>]
                         bind(&ClusterStateController::GetFreshNodes,
                         ^
/usr/include/c++/v1/type_traits:424:28: note: candidate template ignored:
      substitution failure [with _Tp = std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> > () const]: reference to
      function type 'std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> > () const' cannot have 'const'
      qualifier
template <class _Tp> _Tp&  __source();
                     ~~~   ^
cpp/server/server.cc:248:20: error: no matching constructor for initialization
      of 'cert_trans::Proxy'
  proxy_.reset(new Proxy(event_base_.get(),
                   ^     ~~~~~~~~~~~~~~~~~~
./cpp/server/proxy.h:38:3: note: candidate constructor not viable: no known
      conversion from '__bind<std::__1::vector<ct::ClusterNodeState,
      std::__1::allocator<ct::ClusterNodeState> >
      (cert_trans::ClusterStateController::*)() const,
      cert_trans::ClusterStateController *>' to 'const GetFreshNodesFunction'
      (aka 'const function<std::vector<ct::ClusterNodeState> ()>') for 2nd
      argument
  Proxy(libevent::Base* base, const GetFreshNodesFunction& get_fresh_nodes,
  ^
./cpp/server/proxy.h:51:28: note: candidate constructor not viable: requires 1
      argument, but 4 were provided
  DISALLOW_COPY_AND_ASSIGN(Proxy);
                           ^
./cpp/base/macros.h:8:3: note: expanded from macro 'DISALLOW_COPY_AND_ASSIGN'
  TypeName(const TypeName&) = delete;      \
  ^
2 errors generated.
`

**Comment by stas730** [comment]
P. S. I added (or modified) lines from configure-ct to Makefile.

**Comment by stas730** [comment]
P. P. S. Configure from configure-ct fails. :(

**Comment by stas730** [comment]
Waiting for reply…

**Comment by eranmes** [comment]
We'd be happy to help - on the mailing list. Marking this issue as closed because it does not indicate any particular issue or bug with our code/ build configuration (it would be different if the report was failure to build due to a specific configuration).

Please follow up on the certificate-transparency@googlegroups.com mailing list.

**Comment by stas730** [comment]
@pphaneuf can help me.
I CANNOT CREATE GOOGLE ACCOUNT.

**Comment by stas730** [comment]
Can help me in this issue*
