### ISSUE TITLE
Move golang client response data structures into a proto

### ISSUE THREAD

**Issue by gdbelvin** [google/certificate-transparency#1223]

**Comment by pphaneuf** [comment]
Any more details or motivation? Those responses don't usually get serialized, and in Go, the generated code for the in-memory structure is pretty much a simple in-memory structure, isn't it?

I'm trying to get away from protobuf where they're not of benefit, for example in Java (but C++ is coming too): https://github.com/google/certificate-transparency/compare/master...pphaneuf:java_dev
