### ISSUE TITLE
Not user-friendly. README — errors.

### ISSUE THREAD

**Issue by stas730** [google/certificate-transparency#1226]
I'm doing rm -rf * .gclient and syncing again. CT code is VERY HARD to compile. We need to create more user-friendly README.
Now I'm trying to compile code without help.

**Comment by eranmes** [comment]
What parts of the README is unclear? what exactly is not user friendly about it?

**Comment by stas730** [comment]
Because I doing steps explained in README. And see errors. My OS is Ubuntu-based.

**Comment by stas730** [comment]
I compiled it with GCC.
