### ISSUE TITLE
Mailing lists on google website — not good idea

### ISSUE THREAD

**Issue by stas730** [google/certificate-transparency#1227]
I compiling without help now. I cannot use mailing list. I send message, but it not appear on the website. Better idea is create GNU Mailman mailing list.
P. S. For privacy reasons I cannot create Google account. I deleted password from old account, but not deleted account.

**Comment by pphaneuf** [comment]
I think you should be able to join without a Google account by sending an email to `certificate-transparency+subscribe@googlegroups.com`? Note the `+subscribe` part, it is important!

This mailing list is moderated, so the first emails that you send will not appear immediately, this is normal. One of us will see that the emails are not spam, and set a "posting allowed" flag on your email address, so future emails will appear quickly.

**Comment by stas730** [comment]
I sent message successful.
