### ISSUE TITLE
Tutorial on c-t.org for verifying CT in Chrome is out of date

### ISSUE THREAD

**Issue by phad** [google/certificate-transparency#1263]
here: https://www.certificate-transparency.org/certificate-transparency-in-chrome

**Comment by eranmes** [comment]
Would be helpful to know which bits are :)
Also, the detailed SCT info in DevTools change has landed, I should update the page with that.

**Comment by phad** [comment]
The original reporter was a bit vague :)
"I've just realised that the tutorial to verify Certificate Transparency on certificate-transparency.org is not up to date with the latest Chrome UI update which modified a lot of things."

**Comment by RJPercival** [comment]
I've added a screenshot that shows the new DevTools UI for CT.
