### ISSUE TITLE
Go tests for merkletree fail

### ISSUE THREAD

**Issue by phad** [google/certificate-transparency#1270]
$ go test ./...
ok  	_/usr/local/google/home/hadfieldp/ct/certificate-transparency/go	0.862s
ok  	_/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/asn1	0.050s
ok  	_/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/client	15.095s
ok  	_/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/fixchain	0.242s
?   	_/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/fixchain/main	[no test files]
ok  	_/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/fixchain/ratelimiter	27.779s
ok  	_/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/gossip	5.962s
?   	_/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/gossip/main	[no test files]
--- FAIL: TestAddLeaf (0.00s)
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
	panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 6 [running]:
panic(0x57cb80, 0xc82000a620)
	/usr/lib/google-golang/src/runtime/panic.go:483 +0x3ef
testing.tRunner.func1(0xc82001c120)
	/usr/lib/google-golang/src/testing/testing.go:467 +0x192
panic(0x57cb80, 0xc82000a620)
	/usr/lib/google-golang/src/runtime/panic.go:443 +0x4f2
_/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/merkletree.(*CPPMerkleTree).CurrentRoot(0xc8200103e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/merkletree/merkle_tree.go:55 +0x15e
_/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/merkletree.TestAddLeaf(0xc82001c120)
	/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/merkletree/merkle_tree_test.go:79 +0x481
testing.tRunner(0xc82001c120, 0x87eed8)
	/usr/lib/google-golang/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/lib/google-golang/src/testing/testing.go:587 +0x892
FAIL	_/usr/local/google/home/hadfieldp/ct/certificate-transparency/go/merkletree	0.026s

**Comment by AlCutter** [comment]
Yeah, this is due to the way we're allocating/passing memory between the go runtime and C++.
As a workaround you can run your tests like so: `GODEBUG=cgocheck=0 go test ./...`
