### ISSUE TITLE
limit HTTP headers and URL size.

### ISSUE THREAD

**Issue by ytrezq** [google/certificate-transparency#1273]
Sorry but I couldn’t found informations about this *(as the directory layout in undocumented)*

What’s the purpose of the evhtp web server in the project ? What is it used for ?

**Comment by pphaneuf** [comment]
The Certificate Transparency log server protocol is that of an HTTP service (see RFC 6962 for more information), so there *is* an HTTP server, but we still use the one that's included with the `libevent` stable releases.

We do use `evhtp` in the HTTP client:

https://github.com/google/certificate-transparency/blob/master/cpp/net/url_fetcher.cc

We had to use it because of (at least) these problems with the HTTP client included in `libevent`:

https://github.com/libevent/libevent/issues/216
https://github.com/libevent/libevent/issues/217

**Comment by ytrezq** [comment]
@pphaneuf : last question : what is the maximum value of the ᴜʀʟ length for the ʜᴛᴛᴘ server ?

**Comment by pphaneuf** [comment]
From some reading of the current version of the `libevent` code, "very large". Large enough that I'm thinking we should limit it (using `evhttp_set_max_headers_size`).

**Comment by ytrezq** [comment]
@pphaneuf : Please let me do it !

The only question is what should the limit values for ʜᴛᴛᴘ 413 and ʜᴛᴛᴘ 414 return codes.

**Comment by pphaneuf** [comment]
Sure, feel free to send in a pull request! Make sure you have the appropriate CLA signed, as explained in the [CONTRIBUTING.md](https://github.com/google/certificate-transparency/blob/master/CONTRIBUTING.md) file.

The request line should never be too long (there are not many possible parameters), but that setting in `libevent` is shared with the maximum length of each header, so it should still be fairly generous (some cookies and user-agent strings are remarkably long!), maybe something like 4 kilobytes?

For the POST body, 32 kilobytes should be sufficient, without allowing much abuse?

It should be fine to put this in some central location, like `libevent_wrapper.cc`.

**Comment by ytrezq** [comment]
However, as a student, it might take a week or two. Please stay patient.

**Comment by pphaneuf** [comment]
Sure.

**Comment by ytrezq** [comment]
@pphaneuf : why did you not assign to me ?

**Comment by pphaneuf** [comment]
I tried that first, but it wouldn't let me assign it to someone who's not a member of the project. So I took it, that way it doesn't show up as unassigned, and it'll remind me to keep an eye on this in a few weeks, if I haven't heard back. 😉

**Comment by ytrezq** [comment]
Finally might need 4 more days…

**Comment by ytrezq** [comment]
@pphaneuf : pull request #1289 opened.

**Comment by ytrezq** [comment]
@pphaneuf : pull request #1289 opened. Seems ready to get merged.

**Comment by pphaneuf** [comment]
Sorry, I've been rather busy, but I'll check those out soon!

**Comment by ytrezq** [comment]
@pphaneuf  : should this be considered as fixed ?

**Comment by pphaneuf** [comment]
Sounds like it!
