### ISSUE TITLE
How to parse `get-entries` result?

### ISSUE THREAD

**Issue by semaj** [google/certificate-transparency#1277]
After base64 decoding the result of a `ct/v1/get-entries` GET request (made to say, aviator) how do I parse the `leaf` structure of one of the results? Can I get it into a well-known OpenSSL format?

Thanks!

**Comment by eranmes** [comment]
https://tools.ietf.org/html/rfc6962#section-4.6 specifies the format of the response. You have to do some parsing manually or use one of the client libs in this repository - I'm not aware of a way to feed it as-is to OpenSSL.
Such questions are more suitable for the mailing list. Closing.
