### ISSUE TITLE
[C++, Go] Inclusion Proof fails for leaf_index = 0

### ISSUE THREAD

**Issue by gdbelvin** [google/certificate-transparency#1278]
Returning a leaf index of 0 is a valid CT response, per the [RFC](https://tools.ietf.org/html/draft-ietf-trans-rfc6962-bis-17#section-10.4.1), and is the index of the first entry.  

SCT:
`{"tree_size":1,"timestamp":1469742447178,"sha256_root_hash":"4OEMvu0pQwiIBmNv8x+7ivc10k6j0yTuSsmRA3ZPmes=","tree_head_signature":"BAMARTBDAiAiVLelb8WoTpu4JnCaiAVFBZyPrVuNrdXJzlHr2qy49QIfbHdVQRYnOjFsBtduv+7NubX5xhLTPEy9nKtRyueqwA=="}`

Proof By Hash:
`/ct/v1/get-proof-by-hash?hash=4OEMvu0pQwiIBmNv8x%2B7ivc10k6j0yTuSsmRA3ZPmes%3D&tree_size=1`
`{"leaf_index":0,"audit_path":[]}`

The python implementation follows the RFC algorithm and verifies, but the Go and C++ implementations do not.

**Comment by Martin2112** [comment]
Not sure what you mean so I'll take a guess. An audit path is the list of
additional nodes that you need to verify the hash. There aren't any
additional nodes in a single leaf tree.

In RFC 6962 section 2.1.1 it says:

"The path for the single leaf in a tree with a one-element input list
   D[1] = {d(0)} is empty:

   PATH(0, {d(0)}) = {}"

Or do you mean something else? Have you got some code?

Martin

**Comment by gdbelvin** [comment]
I have a PR for the Go code on the way :-)

**Comment by pphaneuf** [comment]
Your first comment there says "SCT" at the top, but did you really mean that, or did you mean STH? It really looks like an STH. :smiley: 

And you're right, a tree of size 1 has a root hash that's equal to the leaf hash of the only entry in it, and if you ask an inclusion proof for that entry, you'll get an empty audit path. Basically, your algorithm can be simply "for each entry in the audit path, combine it with the hash, and make that the new hash", with this case being that you don't do anything, and your initial hash is your root hash.

I wasn't even sure whether there was any code doing inclusion checks in C++ (which function/class were you using in C++ that showed the bug?) or Go, so I'll take it on good faith that there are and that they are buggy. :smiley:

**Comment by gdbelvin** [comment]
https://github.com/google/certificate-transparency/blob/cdde1f2345c95ca633514b5c105a13b4e97e2937/cpp/merkletree/merkle_verifier.cc#L34

go/merkletree/merkle_verifier.go L50
