### ISSUE TITLE
Golang: Handle backoffs on a per-log basis

### ISSUE THREAD

**Issue by jsha** [google/certificate-transparency#1324]
Right now the Golang client has nice backoff logic for 503's, respecting Retry-After. However, when submitting requests from many goroutines, this backoff logic won't be as effective. One goroutine might be in backoff mode, while a hundred others are still sending requests.

Proposal:

Maintain a map of `sync.WaitGroup`, indexed by either log URL. Each request checks this map before firing, and `Wait()`s on the relevant entry. Normally this completes right away; however, any request that gets a 503 calls `wg.Add(1)`, then calls `wg.Done()` once it gets success or non-retryable error. That way all requests to the same log wait until the 503 condition clears.

**Comment by daviddrysdale** [comment]
Making the backoff cope better with multiple goroutines sounds like a good idea, but I'm not sure about using a `sync.WaitGroup` to do it -- won't that fall foul of the restriction that ["calls with a positive delta that occur when the counter is zero must happen before a Wait."](https://golang.org/pkg/sync/#WaitGroup.Add)?

Have you got a sample implementation?  (And does it test OK with `-race` ?)

(Also, sorry for the delay in responding.)

**Comment by jsha** [comment]
Good point about the `sync.WaitGroup` semantics. We'd have to find an alternate approach. I don't have a sample implementation yet. Was waiting to hear whether this was something you'd want in the library. Good to know you do, so we can try to implement as we have time. Thanks1

**Comment by rolandshoemaker** [comment]
Took a stab at this, would be interested in peoples thoughts on the implementation. This moves the backoff to a per-`JSONClient` basis instead of per-`PostAndParseWithRetry` (note I haven't updated the existing backoff test, this is just a rough implementation).

The one thing I'm not super sure about is that this basically ignores the `Retry-After` header if it is set on `503` responses which is _probably fine_ but I'm not 100% sure.

https://github.com/google/certificate-transparency-go/compare/master...rolandshoemaker:per-log-backoff?expand=1

**Comment by jsha** [comment]
My opinion: If a log operator went to the trouble to set a Retry-After header, the library should definitely obey it. This also provides a convenient way for log operators to ask submitters (like us) to back off using config solely on their side, rather than asking us to change our configuration.

Also, this branch seems to switch from exponential to linear backoff. I think it would be better to just change the behavior to be per-client without changing the backoff algorithm, and if you want to also change the backoff algorithm, propose it in a separate change.
