### ISSUE TITLE
go/client should use context.Context consistently

### ISSUE THREAD

**Issue by daviddrysdale** [google/certificate-transparency#1326]
Current status is that:
 - Some `LogClient` methods take a `context.Context`:
     - `GetSTHConsistency`
     - `GetProofByHash`
     - `LogClient.AddChainWithContext` (but there is no `AddPreChainWithContext`)
 - Some do not:
    - `GetSTH`
    - `AddPreChain`
    - `AddChain`
    - `AddJSON`

It would be nicer if everything took a `context.Context` parameter.

**Comment by rolandshoemaker** [comment]
Is there consensus on how to implement this change? It seems like as `context` has been moved into the stdlib in 1.7 it'd make sense to remove the `...WithContext` method and just make everything take a `context.Context` as it's first parameter. This would be a breaking change but would standardize the packages behavior substantially.

**Comment by daviddrysdale** [comment]
Sounds sensible to me -- everything takes a (non-`nil`) `ctx context.Context` as its first parameter, and the separate `AddChainWithContext` drops out.

For the moment the context would presumably come from `import "golang.org/x/net/context"` and we'd expect to shift to plain `import "context"` at some point in the future (when we shift to requiring go 1.7), yesno?

**Comment by rolandshoemaker** [comment]
> For the moment the context would presumably come from import "golang.org/x/net/context" and we'd expect to shift to plain import "context" at some point in the future (when we shift to requiring go 1.7), yesno?

Yeah I think just using `x/net/context` is the simplest solution for now, perhaps once 1.8 is out it'd be safe to switch to the stdlib implementation (it'd also be possible to use [the method `x/net/http2` uses](https://github.com/golang/net/search?q=contextContext) but it'd be a bit more convoluted).
