### ISSUE TITLE
GetProofByHash() get 400 bad request

### ISSUE THREAD

**Issue by hsulei** [google/certificate-transparency#1358]
when i use GetProofByHash() to get some information ,i get a 400 bad request, is my code having problem?
```go
 httpClient := &http.Client{
		Transport: &httpclient.Transport{
			ConnectTimeout:        10 * time.Second,
			RequestTimeout:        30 * time.Second,
			ResponseHeaderTimeout: 30 * time.Second,
			MaxIdleConnsPerHost:   10,
			DisableKeepAlives:     false,
		},
	}


	var opts jsonclient.Options
	test := struct {
		hash     []byte
		treesize uint64
	}{
		dh("B97BC04FB360FDE677BE257A70E7141EB6C8520DB46450AB85786D410C22B3AE"),
		3,
	}

	client, err := client.New("http://ct.googleapis.com/aviator", httpClient, opts)
	if err != nil {
		log.Warnf("JsonClient err：%v", err)
		return
	}
	ctx := context.Background()
	resp, err := client.GetProofByHash(ctx, test.hash, test.treesize)
	if err != nil {
		log.Warnf("Proof err ：%v", err)
		return
	}

```

**Comment by daviddrysdale** [comment]
Using your values I see an error message of:
```
Hash is unknown : generic::failed_precondition: Leafhash (b97bc04fb360fde677be257a70e7141eb6c8520db46450ab85786d410c22b3ae) not in index
```
Where do you get your hash value and tree size?   (A tree size of 3 seems low -- is the hash really from one of the first couple of entries in the log?)

(Building the leaf hash can be a bit fiddly, BTW -- there's an example [here](https://github.com/google/trillian/blob/master/integration/ct_integration_test.go#L270-L286) of hash generation).)

**Comment by hsulei** [comment]
whatever i change the value of `treesize` ,i can't get the err message that you get ,i use `GetGetSTH()`to get `treesize`  ，the treesize is `46466472 `, `sha256.Sum256()`  calculate `leaf hash`, but the `GetProofByHash ()` response  still is `got HTTP Status "400 Bad Request" ` 。is the `GetProofByHash()` use a mistake way？ or i miss some config?

**Comment by daviddrysdale** [comment]
What do you use as the input to `sha256.Sum256`?  As per [RFC 6962 s2.1](https://tools.ietf.org/html/rfc6962#section-2.1) and [s3.4](https://tools.ietf.org/html/rfc6962#section-3.4), the input to the hash function needs to be 0x00 followed by a TLS-encoded `MerkleTreeLeaf`.

**Comment by hsulei** [comment]
can i use `certificate sha256 fingerprint` to check this certificate is or isn't in ct logs？, and in `RFC 6962` i can't find `/ct/v1/add-json`

**Comment by eranmes** [comment]
No, you cannot. You have to  submit the certificate (and the chain) using `/ct/v1/add-chain`.
I'm marking this issue as closed because it doesn't seem like a problem with the client code.
Please do follow up on the mailing list (certificate-transparency@googlegroups.com) with questions about calculating leaf hashes.
