### ISSUE TITLE
TN Authorization List

### ISSUE THREAD

**Issue by preethamshyam7** [google/certificate-transparency#1380]
Hi ,

I need to edit the code and add an OID syntax. So when the certificate generates this OID should be included in my certificate. But this OID is not supported by letsencrypt. So im trying to add this as a static string or any kind of data in my generated certificates. But i want this in my certificates.

TNAuthorizationList ::= SEQUENCE SIZE (1..MAX) OF TNEntry

TNEntry ::= CHOICE {
spid [0] ServiceProviderIdentifierList,
range [1] TelephoneNumberRange,
one E164Number }
Im new to go language. How and which file i need to add this syntax to get this in my certificate.

Thanks in advance.

**Comment by eranmes** [comment]
Sorry, but this seems unrelated to Certificate Transparency.
Looks like you're asking about manipulating X.509 TBSCertificate that would go in a Certificate Signing Request and you'd like fields in there that Let's Encrypt does not add.
I suggest reaching out to other CAs who may have the ability to issue such certificates.
