### ISSUE TITLE
gclient sync error

### ISSUE THREAD

**Issue by CBonnell** [google/certificate-transparency#1398]
It appears that a recent change to `gclient` (https://chromium-review.googlesource.com/c/509451/) has enabled syntax validation of DEPS files by default. This causes an error to occur when processing the DEPS file:

```
ValueError: unexpected AST node: <_ast.Import object at 0x7fd8492ad990> Import(names=[alias(name='os', asname=None)]) (file '/ct/certificate-transparency/DEPS', line 58)
```

Passing `--disable-syntax-validation` to the `gclient sync` command resolves the error. Either the DEPS file should be updated such that it passes validation or the documentation should be updated to specify passing `--disable-syntax-validation` to `gclient sync`.

**Comment by nettrino** [comment]
I got the same error when removing ` --disable-syntax-validation` after getting an initial `gclient.py: error: no such option: --disable-syntax-validation`
