### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by IanLee1521** [google/certificate-transparency#1418]
Hi there -- This may not be the best place to open this, but I couldn't find a better one... 

On https://www.certificate-transparency.org/benefits there is a link to this code:

> We are also actively working on monitoring and auditing software, which you can find at https://code.google.com/p/certificate-transparency/.

Pretty sure that should now be a link to this repo instead.

**Comment by pphaneuf** [comment]
Thanks, fixed it now!
