### ISSUE TITLE
Hi, Everyone - How to get Base64 Log ID

### ISSUE THREAD

**Issue by homepc91** [google/certificate-transparency#1424]
Hi, Everyone
I want to know that....How to know or get that Base64 Log ID..?

**Comment by pphaneuf** [comment]
I answered this here:

https://groups.google.com/d/msg/certificate-transparency/VfppgRLCMY4/cJ53UyDIAgAJ

**Comment by homepc91** [comment]
Okay thanks brother, but other company have base64 id?

You can see in this link:  https://www.certificate-transparency.org/known-logs

![screen shot 2017-11-21 at 1 46 55 am](https://user-images.githubusercontent.com/25889886/33039566-61bb5bb2-ce5e-11e7-99df-429baddf15ff.png)
