### ISSUE TITLE
Log Name and Validation Status not showing.

### ISSUE THREAD

**Issue by homepc91** [google/certificate-transparency#1428]
Hii Everyone's....

I need one more help from you.... I am not getting or see Log Name and Validation Status. I am sending screenshots of my problem.

Please help and guide me.

![screen shot 2017-11-22 at 9 37 40 pm](https://user-images.githubusercontent.com/25889886/33209429-bc6cc0e8-d13b-11e7-83bc-5ebff23b39dc.png)

**Comment by grandamp** [comment]
I would assume this Log Id is unknown to the browser, so the browser is unable to find a display name for the log.
