### ISSUE TITLE
"Failed to determine suitable serving STH." when starting new mirror

### ISSUE THREAD

**Issue by lanrat** [google/certificate-transparency#1439]
Hello,

I'm having difficulty running a local ct-mirror for testing. After reading the documentation and lots of trial and error, I get the ERROR/WARNING: `Failed to determine suitable serving STH.`

Logs:
[ct-mirror.WARNING](https://gist.github.com/lanrat/d63643677b0e56fb37a5ce00abbc06a9#file-ct-mirror-warning)
[ct-mirror.INFO](https://gist.github.com/lanrat/d63643677b0e56fb37a5ce00abbc06a9#file-ct-mirror-info)

I also built and ran ct-mirror inside of Docker with [this Dockerfile](https://gist.github.com/lanrat/d63643677b0e56fb37a5ce00abbc06a9#file-docekrfile). It was modeled after the build instructions and Dockerfiles within the project.

This could be due to something I overlooked on my end. If so, a pointer in the correct direction would be appreciated.

**Comment by lanrat** [comment]
Turns out it took 6+ hours for my mirror to fully clone the source and start working. It would be nice if there was log logging info about the progress if the mirroring process other than this error.

**Comment by donnakids2018** [comment]
Google github.com/google/certificate
