### ISSUE TITLE
Requirements for installing with python3 can't be fullfilled

### ISSUE THREAD

**Issue by aseques** [google/certificate-transparency#1471]
I am trying to install certificate-transparency git master on a ubuntu 19.04 with python3, when obtaining the requirements it fails because (I might be wrong) cStringIO is not available anymore on python3 as a standalone module.
> $ pip3 install -r requirements.txt
> Collecting git+https://github.com/google/google-visualization-python.git@04e4c03909980bc12be2ebb3ecf476716d9855d4 (from -r requirements.txt (line 4))
>   Cloning https://github.com/google/google-visualization-python.git (to revision 04e4c03909980bc12be2ebb3ecf476716d9855d4) to /tmp/pip-req-build-5vgx3vl_
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-req-build-5vgx3vl_/setup.py", line 23, in <module>
>         import gviz_api_test
>       File "/tmp/pip-req-build-5vgx3vl_/gviz_api_test.py", line 30, in <module>
>         from gviz_api import DataTable
>       File "/tmp/pip-req-build-5vgx3vl_/gviz_api.py", line 30, in <module>
>         import cStringIO
>     ModuleNotFoundError: No module named 'cStringIO'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-5vgx3vl_/
>

**Comment by RJPercival** [comment]
I'm afraid our Python code doesn't support Python 3. You'll have to use Python 2. Feel free to send us PRs to make it work with Python 3 though.

**Comment by yan-foto** [comment]
The `requirements.txt` seems to be a mess at the moment. Even if you use python 2, i.e., `python2.7 -m pip install -r requirements.txt`, some dependencies, e.g., `jsonschema` does not support python 2 anymore in their latest versions. I can confirm that `jsonschema 2.6.0` is compatible with python 2.7.
