### ISSUE TITLE
Wrong certificate transparency log log_list.json was served from cache

### ISSUE THREAD

**Issue by yvesf** [google/certificate-transparency#1476]
We hope that this issue tracker is monitored by a person who feels responsible for this service. Any help to forward this case to the right person would be much appreciated.

We observed on 8th of May 2020 that the service for https://www.gstatic.com/ct/log_list/v2/log_list.json  was under circumstances serving an old file where the updated signature file https://www.gstatic.com/ct/log_list/v2/log_list.sig did not match.

If the resource is requested with the header "Accept-Encoding: gzip" set, we supposedly got the old version of the file where the signature mismatch. For the signature file it made no difference whether the header is set or not. So it looks like there is a proxy server in front which only for the gzipped version served an old version of the document.

We verified this behavior from few different internet connections in central europe. This is a serious problem since there are client libraries (for example https://github.com/babylonhealth/certificate-transparency-android), where the http client downloads this file and then checks the signature. If the signature validation fails then the http client completely stops working.

In a real world example an Android App is simply dysfunctional until the cache issues are resolved.

We couldn't find documentation of the log_list resource that defines if the android library is doing something wrong in the first place by setting the "Accept-Encoding: gzip" header. But it feels that in general it would make sense to always get a matching `.json` and `.sig` pair of files.

From the header `Expires: Fri, 08 May 2020 14:14:55 GMT` below we take that this issue will likely resolves itself (for this time) shortly after this text is published.

Additional debug info: Request without Acccept-Encoding header

```
$ wget --debug https://www.gstatic.com/ct/log_list/v2/log_list.json 
DEBUG output created by Wget 1.20.1 on linux-gnu.
Reading HSTS entries from /home/yvesf/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'log_list.json' (UTF-8) -> 'log_list.json' (UTF-8)
--2020-05-08 13:05:47--  https://www.gstatic.com/ct/log_list/v2/log_list.json
Certificates loaded: 128
Resolving www.gstatic.com (www.gstatic.com)... 172.217.168.3, 2a00:1450:400a:801::2003
Caching www.gstatic.com => 172.217.168.3 2a00:1450:400a:801::2003
Connecting to www.gstatic.com (www.gstatic.com)|172.217.168.3|:443... connected.
Created socket 3.
Releasing 0x00005556820bf5e0 (new refcount 1).
---request begin---
GET /ct/log_list/v2/log_list.json HTTP/1.1
User-Agent: Wget/1.20.1 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: www.gstatic.com
Connection: Keep-Alive
---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Type: application/json
Access-Control-Allow-Origin: *
Content-Length: 26416
Date: Fri, 08 May 2020 09:18:15 GMT
Expires: Sat, 09 May 2020 09:18:15 GMT
Last-Modified: Thu, 07 May 2020 23:15:00 GMT
X-Content-Type-Options: nosniff
Server: sffe
X-XSS-Protection: 0
Cache-Control: public, max-age=86400
Age: 6452
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
---response end---
200 OK
```

Request with `Accept-Encoding: Gzip`
```
$ wget --debug --header="Accept-Encoding: gzip" https://www.gstatic.com/ct/log_list/v2/log_list.json 
Setting --header (header) to Accept-Encoding: gzip
Setting --header (header) to Accept-Encoding: gzip
DEBUG output created by Wget 1.20.1 on linux-gnu.
Reading HSTS entries from /home/yvesf/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'log_list.json' (UTF-8) -> 'log_list.json' (UTF-8)
--2020-05-08 13:06:18--  https://www.gstatic.com/ct/log_list/v2/log_list.json
Certificates loaded: 128
Resolving www.gstatic.com (www.gstatic.com)... 172.217.168.3, 2a00:1450:400a:801::2003
Caching www.gstatic.com => 172.217.168.3 2a00:1450:400a:801::2003
Connecting to www.gstatic.com (www.gstatic.com)|172.217.168.3|:443... connected.
Created socket 3.
Releasing 0x000056400b3e5670 (new refcount 1).
---request begin---
GET /ct/log_list/v2/log_list.json HTTP/1.1
User-Agent: Wget/1.20.1 (linux-gnu)
Accept: */*
Accept-Encoding: gzip
Host: www.gstatic.com
Connection: Keep-Alive
---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Type: application/json
Access-Control-Allow-Origin: *
Content-Length: 26240
Date: Thu, 07 May 2020 14:14:55 GMT
Expires: Fri, 08 May 2020 14:14:55 GMT
Last-Modified: Fri, 07 Feb 2020 16:15:00 GMT
X-Content-Type-Options: nosniff
Server: sffe
X-XSS-Protection: 0
Age: 75083
Cache-Control: public, max-age=86400
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
---response end---
200 OK
```

The difference in the response (diff from older one to newer):
```
--- older	2020-05-08 13:04:28.600807382 +0200
+++ newer	2020-05-08 13:04:24.744790677 +0200
@@ -302,8 +302,12 @@
           "url": "https://ct2.digicert-ct.com/log/",
           "mmd": 86400,
           "state": {
-            "usable": {
-              "timestamp": "2017-10-10T00:38:10Z"
+            "readonly": {
+              "timestamp": "2020-05-04T00:00:00Z",
+              "final_tree_head": {
+                "sha256_root_hash": "CbUBsYFOJysvawCKgFUJZolODUDjWU8bActeOm+itCc=",
+                "tree_size": 90271162
+              }
             }
           }
         },
```

**Comment by dlmr** [comment]
We observed that `www.gstatic.com` resolves to two different IPs (`216.58.211.3` & `172.217.22.35`), only one the latter one having this issue. This means that it seems to sometimes work and sometimes not. 

```sh
curl -k -H 'Accept-Encoding: gzip' -H 'Host: www.gstatic.com' https://172.217.22.35/ct/log_list/v2/log_list.json > 172
curl -k -H 'Accept-Encoding: gzip' -H 'Host: www.gstatic.com' https://216.58.211.3/ct/log_list/v2/log_list.json > 216
```

```sh
diff 172 216

305,306c305,310
<             "usable": {
<               "timestamp": "2017-10-10T00:38:10Z"
---
>             "readonly": {
>               "timestamp": "2020-05-04T00:00:00Z",
>               "final_tree_head": {
>                 "sha256_root_hash": "CbUBsYFOJysvawCKgFUJZolODUDjWU8bActeOm+itCc=",
>                 "tree_size": 90271162
>               }
```

This also means that the good one might become bad when it expires at `Sat, 09 May 2020 02:55:28 GMT`.

**Comment by ctaintor** [comment]
Just for more information, the object that is different it related to `DigiCert Log Server 2`. We noticed that this log server will soon be retired, hence it is probably related. Perhaps more context [here](https://groups.google.com/a/chromium.org/forum/#!topic/ct-policy/f_OpqFEZT9M)

**Comment by jwagner** [comment]
Just a little side note for clarity. The constraint of always getting a matching *.sig for the corresponding .json cannot be guaranteed with the "Cache-Control: public, max-age=86400" cache policy. The Accept-Encoding: gzip is just one case where they happened to diverge but there is no guarantee for other cases either. 

I guess In practice the easiest solution would be to have a ".sig.json" file which provides both the signature and a unique url for the file that is signed (say containing the hash that was used for signing):

```http

GET /ct/log_list/v2/log_list.sig.json

{
  "signature": "ZWwY9wHJh7DqYKkk3AdJI8owiz1Ibl4kG742IKbq34I+Lrya5rcbEFZ54rL0tzNYVkpOiFil4bmG
KsBz9R0aFsUobF2uig6m/JI9TV7WQvk2rCzmcdRklqbJ3Q/L0YBfQFujl/9zuKzI7K9J4xWlQnSf
onrXe1YxGohL9kHgGlYIortiCbOBY8EPvwWwJGMO8T6d09/SNR7uniMuBpkXhdQm6gi4r595YwxH
HWpScJjeo5raWw3FKPKx4BdcYR8/CL5DurdZRFZT/1TYrAvCdaW4rNPePSnbSgYAVIgNUdSsFkoV
u78s9BxU3p4EXyDmROCJzwZlo95jucy6y6VvS3Y62t7isARO11zB2Fjtkkozn6zq/oKXXVLVRMcc
3tKuiJZsm8WKxYGulhh+YoV6PCfVqwrZY/4E9PMgVzzyai3V24KinrZjukPdhB5xXm0jkiRDfCYv
bVRLVxkC6JFCKe4GTi9Sj6W3WMyXBWLhczYy5iAOMx3MJYiol28cql1rTAzu1Hwh4/qGxLQ9JBzw
qYAkW8utYkkoonQOvIDHbPWwyYtyFyrwXCmhUjFB5cIBGHR8WryLgDYUa6x1s5bpeqRbzAfg5lLF
Jf9yv+puYV/oUYQocXj2uukPgQrS2ZMuvwJZcBf5i0jFwt+UCq9lFQBl8dAn7tR3lhv8Y+BiUO4=",
  "url": "https://www.gstatic.com/ct/log_list/v2/log_list-ZWwY9wHJh7Dq.json"
}
```

That would require an additional round trip for clients however. To avoid that and keep http cache semantics intact the two would need to be bundled into a single resource but that can be fiddly for the consumers (correctly verifying the signature on a subset of a json).

**Comment by taknira** [comment]
Hi everyone,

We have reduced the max caching time of these files to one hour, to
minimise the window during which this out-of-sync behaviour could occur.

We will look into possible ways of bundling the two files together, so that
any update will be either seen or not seen consistently across both files,
as well as making historical versions of the list available so that clients
can always backtrack to the previous version that verified if need be.
Hopefully for now this cache time reduction will improve the situation for
those consuming the json log list and signature.

Thanks,
Kat

**Comment by ctaintor** [comment]
Thanks @taknira - is there any rough estimate on when a full fix will be available? We're looking into our options since even the mitigation leads to a signifiant number of users being affected. Before we implement our own distribution of these files, I'd like to understand if waiting is a better idea.

**Comment by kpmmmurphy** [comment]
Hey @taknira, thanks for tackling this. Is there any progress on resolving it fully? We experienced the out of sync issue again yesterday. It did only last for an hour, which is an improvement, but still affected some users!

**Comment by taknira** [comment]
Hey - firstly, apologies, I thought I had posted our plans on here already, but apparently not!

We have been implementing a solution to serve log_list.json and log_list.sig together in a zip file alongside the two existing files.  We are in the very final stages of implementing this, and are hoping to have said zip file being published to gstatic by the end of this week.

I'll post back here again and announce it on the ct-policy group once the zip file is live.

Thanks everyone for your patience with this!

**Comment by taknira** [comment]
Hi everyone,

We are now publishing a zip file containing both the log_list.json and log_list.sig files, which you can find at http://www.gstatic.com/ct/log_list/v2/log_list.zip.

Hopefully this solves the problem!
