### ISSUE TITLE
A Error when i am try build.

### ISSUE THREAD

**Issue by anye-dark** [google/certificate-transparency#1479]
When I input the command "gclient sync --disable-syntax-validation", gclient prompts the following error:
gclient.py: error: no such option: --disable-syntax-validation

**Comment by anye-dark** [comment]
Why is there no "--disable-syntax-validation" parameter for the gclient sync command?

**Comment by Martin2112** [comment]
Hi,

This code is no longer being actively worked on.  There is a new implementation of CT at:

https://github.com/google/certificate-transparency-go

**Comment by anye-dark** [comment]
Okay. Thank for your help. I will try it.
