### ISSUE TITLE
CT make test error with binary openssl

### ISSUE THREAD

**Issue by seroscar2** [google/certificate-transparency#150]
With a "Build successful" compilation of CT, I try to test the installation, going to /test, and executing: 	make OPENSSLDIR=”/usr/local/ssl” GTESTDIR=”/home/izenpe/CT/gtest-1.6.0” test
I am using a default binary installation of openssl, so I don't have the /usr/local/ssl/apps/openssl directory. The error it shows is:

BUILD SUCCESSFUL
Total time: 2 seconds
make[2]: Entering directory `/home/izenpe/CT/certificate-transparency/python'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/izenpe/CT/certificate-transparency/python'
make[1]: Leaving directory `/home/izenpe/CT/certificate-transparency'
OPENSSLDIR=/usr/local/ssl ./sslconnect_test.sh
./sslconnect_test.sh: line 114: /usr/local/ssl/apps/openssl: No such file or directory
make: *** [test] Error 127

Is there any way to execute these tests with a binary installation of openssl?. I have downloaded the CT source code using git.
Thanks

**Comment by eranmes** [comment]
Do you still experience this issue? we've re-organized the files a bit since then, including the makefiles and shellscripts used to run the tests.
If so, please re-open with an up-to-date error log.
