### ISSUE TITLE
should not CHECK-fail when connecting to etcd fails

### ISSUE THREAD

**Issue by pphaneuf** [google/certificate-transparency#303]
Running ```etcd_watch``` without a running ```etcd``` gets you a CHECK failure:

    F1205 16:15:22.459904  3694 etcd.cc:794] Check failed: 'evhttp_find_header(req->GetInputHeaders(), "X-Etcd-Index")' Must be non NULL

**Comment by AlCutter** [comment]
Pretty sure this doesn't happen how.
