### ISSUE TITLE
Add support for monitoring

### ISSUE THREAD

**Issue by AlCutter** [google/certificate-transparency#405]

**Comment by eranmes** [comment]
Where? For what?

**Comment by pphaneuf** [comment]
We're using the issues here to remember things. First step is going to be "figure out what and where", I think. :smiley:

**Comment by pphaneuf** [comment]
You've got some sort of support for monitoring... You're clearly on top of this, so assigning to you, but I'll let you decide if you're sufficiently done to close this one. :smiley:

**Comment by AlCutter** [comment]
We have support for prometheus now, need to build on it a bit - e.g. pre-packaged config with alerts etc. but we'll open separate issues for those things.
