### ISSUE TITLE
Make Follower Peer interact somehow with ClusterStateController

### ISSUE THREAD

**Issue by AlCutter** [google/certificate-transparency#407]
for up-to-date info about peers (starting/stopping etc.)

**Comment by pphaneuf** [comment]
Hmm, don't we have that? The ClusterStateController is the one adding and removing peers from the continuous fetcher...

https://github.com/google/certificate-transparency/blob/super_duper/cpp/log/cluster_state_controller-inl.h#L227

**Comment by AlCutter** [comment]
I think this was just recording a conversation we had about how stuff would work, but as you say it's there now !
