### ISSUE TITLE
initialize TreeSigner and LogLookup together

### ISSUE THREAD

**Issue by pphaneuf** [google/certificate-transparency#428]
At startup, they both need to iterate over the whole data set, in index order. Maybe they could be changed to have entries pushed to them from the database, instead of pulling?

**Comment by pphaneuf** [comment]
Or maybe the Database should maintain a shared merkle tree?

**Comment by pphaneuf** [comment]
That's done, right?

**Comment by AlCutter** [comment]
Yup.
