### ISSUE TITLE
Assertion evcon->state == EVCON_IDLE failed in evhttp_request_dispatch

### ISSUE THREAD

**Issue by AlCutter** [google/certificate-transparency#483]
Saw this line as the dying gasp of a Superduper node:
`I0210 11:18:40.857167    11 log_lookup-inl.h:83] Found 0 new log entries`
`I0210 11:18:40.857188    11 log_lookup-inl.h:90] Tree successfully updated at Tue Feb 10 11:18:40 2015`
`I0210 11:18:43.599652    17 tree_signer-inl.h:236] Building tree starting from 0
[err] http.c:1207: Assertion evcon->state == EVCON_IDLE failed in evhttp_request_dispatch
Aborted`

**Comment by pphaneuf** [comment]
I curse myself for this "thin libevent wrapper"... Hope exists, in the ```net_fetcher``` branch in my repo, I'll get to that at some point soon.

**Comment by pphaneuf** [comment]
I'm not even sure who called this, but I think 10bca189865087ce5d2d5fa0ca256c8d8c33257b should have fixed it anyway (or changed it into a different bug!).
