### ISSUE TITLE
handle failure of the initial get in etcd watch more cleanly

### ISSUE THREAD

**Issue by AlCutter** [google/certificate-transparency#488]
`I0211 10:43:06.002665     9 continuous_fetcher.cc:112] starting fetch with tree size: 0`
`W0211 10:43:26.403292    17 tree_signer-inl.h:246] problem getting sequenced entry 0: 2: unknown error`

No apparent error in the etcd logs.

**Comment by AlCutter** [comment]
Another one, different place:
```
F0211 10:51:43.595259    10 etcd.cc:550] Check failed: status.ok() initial get error: 2: unknown error
*** Check failure stack trace: ***
    @     0x7ffa09de0daa  (unknown)
    @     0x7ffa09de0ce4  (unknown)
    @     0x7ffa09de06e6  (unknown)
    @     0x7ffa09de3687  (unknown)
    @           0x476ad4  cert_trans::EtcdClient::WatchState::InitialGetAllDone()
    @           0x488c7a  _ZNKSt7_Mem_fnIMN10cert_trans10EtcdClient10WatchStateEFvN4util6StatusERKSt6vectorINS1_4NodeESaIS6_EElEEclIJS4_SA_lEvEEvPS2_DpOT_
    @           0x488bae  std::_Function_handler<>::_M_invoke()
    @           0x488e6d  std::function<>::operator()()
    @           0x47cd5c  cert_trans::(anonymous namespace)::GetAllRequestDone()
    @           0x486598  _ZNSt5_BindIFPFvN4util6StatusERKSt10shared_ptrI10JsonObjectElRKSt8functionIFvS1_RKSt6vectorIN10cert_trans10EtcdClient4NodeESaISB_EElEEESt12_PlaceholderILi1EESM_ILi2EESM_ILi3EESH_EE6__callIvJOS1_S6_OlEJLm0ELm1ELm2ELm3EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @           0x48643a  std::_Function_handler<>::_M_invoke()
    @           0x48595d  std::function<>::operator()()
    @           0x47b210  cert_trans::EtcdClient::RequestDone()
    @           0x473753  cert_trans::libevent::HttpRequest::Done()
    @     0x7ffa08d6c12a  (unknown)
    @     0x7ffa08d618b4  (unknown)
    @           0x472b87  cert_trans::libevent::Base::DispatchOnce()
    @           0x47523f  cert_trans::libevent::EventPumpThread::Pump()
    @     0x7ffa082bcbf0  (unknown)
    @     0x7ffa0a230182  start_thread
    @     0x7ffa07a2400d  (unknown)
    @              (nil)  (unknown)
Aborted
```

**Comment by pphaneuf** [comment]
In ```etcd.cc```, you get that when libevent calls our callback with a null pointer, so we genuinely have no flipping idea what the heck could be going on. I should go read that code, and find out in which case it decides to do that, it can't be "just happening by accident". :wink: 

I think it's also the same error from ```etcd.cc``` bubbling up in ```tree_signer-inl.h```. We could at least put a more useful error string...

**Comment by pphaneuf** [comment]
I went and read that code, and this location is the only spot that calls the callback with a null request:

https://github.com/libevent/libevent/blob/patches-2.0/http.c#L748

From looking at all the callers of ```evhttp_connection_fail```, it seems to happen for just about everything that causes the connection to go bad. Most of those are very bad things, like parse errors, but one of the possibility is when a connection times out (I *really* wish that would have been reported in a separate way!).

From the looks of it, I'd say that you can just retry the request? There's the niggling case of the timeout, but with the way libevent's HTTP client is done, it really means that the *connection* didn't get anything for a while, it might not be your particular request. That would be very interesting to distinguish, but it doesn't seem possible?

**Comment by pphaneuf** [comment]
I popped this as a question to the libevent folks: libevent/libevent#216

**Comment by pphaneuf** [comment]
This does not happen as much, but we should handle failures in the initial get more cleanly, retrying them after a delay, perhaps?
