### ISSUE TITLE
tree_signer_test is flaky

### ISSUE THREAD

**Issue by pphaneuf** [google/certificate-transparency#495]
log/tree_signer_test.cc:259: Failure
    Expected: (sth.timestamp()) < (sth2.timestamp()), actual: 1423763522790 vs 1423763522790
    [  FAILED  ] TreeSignerTest/0.ResumePartialSign, where TypeParam = FileDB<cert_trans::LoggedCertificate> (3 ms)

**Comment by AlCutter** [comment]
Haven't seen this happen in a while, will close for now.

**Comment by pphaneuf** [comment]
I just ran this test 8000 times, it didn't fail once, so I think we're okay.
