### ISSUE TITLE
cleaning should be concurrent to sequencing

### ISSUE THREAD

**Issue by pphaneuf** [google/certificate-transparency#605]
In ```super_duper```, the sequencing and cleaning of replicated entries is done one after the other (in a loop). It's very important to keep etcd as "light" as possible, and not have too many entries there, so both sequencing and cleaning need to happen more aggressively.

The main reason for having them done serially is because they both update the sequence number mapping key, but if the sequencer took care of maintaining the mapping, the cleaning could just proceed as quickly as possible, at the same time.

**Comment by pphaneuf** [comment]
@AlCutter, didn't you do this?

**Comment by AlCutter** [comment]
Yes!
