### ISSUE TITLE
mirroring mode

### ISSUE THREAD

**Issue by pphaneuf** [google/certificate-transparency#615]
We would like to be able to mirror existing logs, without altering the entries or the STHs, so that clients could verify SCTs from the original log against a mirror.

**Comment by pphaneuf** [comment]
I'm picking this up on the basis of the hack that's in my ```test_fetcher``` branch, but it's pretty tenuous.

The main thing that's needed is tracking STHs. We can't just get the latest one and update to that, we need to regularly fetch a new STH, and queue it up, so that we can update our serving STH incrementally (new STHs appearing regularly might make it so that the fetching of entries never "catches up" with them, so if we don't remember intermediate STHs, we could be stuck on an old one for a long time).

**Comment by AlCutter** [comment]
This was done ages ago, closing this out now!
