### ISSUE TITLE
check there are no pending entries in SQLite

### ISSUE THREAD

**Issue by pphaneuf** [google/certificate-transparency#621]
With our new design, we're not putting pending entries in the local SQLite (or FileDB) database any more, so in a case where a user is migrating from ```master``` to ```super_duper```, there might be some pending entries in the database that we simply won't be looking at.

Checking for those at startup and refusing to go on should take care of this (if not outright migrating them to etcd?).

**Comment by AlCutter** [comment]
This can no longer happen because we've changed the SQLite schema.
We'll cover this scenario in the documentation.
