### ISSUE TITLE
improve the UrlFetcher connection pool

### ISSUE THREAD

**Issue by pphaneuf** [google/certificate-transparency#665]
The connection pool is incredibly simplistic, and isn't doing that great of a job. The pool is meant to cause re-use of connections (because closing them leaves the local port unusable for a certain amount of time, which causes that resource to be exhausted if we don't re-use them enough), but the default number of connections kept per host is 4, which means that when we delete entries with a concurrency of 100, we re-use only 4 of those connections, and close the 96 others, which is pretty close to not reusing anything at all!

We should have this be slightly more self-tuning, something like closing connections after some time unused, with only much higher hard limit.

**Comment by AlCutter** [comment]
Mostly addressed by #805 modulo the hard upper limit. Closing for now.
