### ISSUE TITLE
Mirror should verify STH matches the mirror's root hash before making it available.

### ISSUE THREAD

**Issue by AlCutter** [google/certificate-transparency#761]

**Comment by pphaneuf** [comment]
One thing I would have liked was to have the state machine in RemotePeer do a consistency proof.

**Comment by AlCutter** [comment]
There doesn't really seem to be much point in doing that; we're going to download all the entries anyway...

A consistency proof just lets you verify that the tree an STH `B` commits to contains every entry contained in the earlier tree which STH `A` commits to, without having to resort to maintaining the actual trees locally (otherwise it'd suck to be a CT compliant browser, for example :) )

It wouldn't necessarily hurt to do an additional consistency check in `remote_peer`, but, for example, it wouldn't catch the situation where a malicious/broken target log issues STHs `C` and `C'` in quick succession (i.e. quicker than it takes for the mirror to fetch the `B`->`C` entries, integrate them, and shift to `C` as the serving STH.):
```
              C
         ,----o
A     B /
o-----o<
        \
         `----o
              C'
```

Assuming the log had a split-view way of producing consistency proofs between `B` and both `C` and `C'` `remote_peer` would be none the wiser.

#840 is broken, though; the root hash check needs to happen higher up (annoyingly, where I was going to put it originally before I tried to get all clever and keep things "tidy", I'll send a PR to sort that soon.)

**Comment by pphaneuf** [comment]
Yeah, if it's malicious, I'd expect the log to serve the proper proof for `B` -> `C`, and if it's malfunctioning (say, a buggy distributed log server that now has frontends that diverged), then you could still get the correct consistency proof for the STH you just got. The idea was to try to check everything we could, but it does look like it might not help very much.

We could verify that the log ID is as expected, but that's pretty minor.

`LogLookup` will `CHECK`-fail if the data doesn't match up, so we won't ever give out incorrect information, but it'd be nice to be handle this better.

**Comment by AlCutter** [comment]
With #846 we now will reject an STH with an incorrect root for the entries we've pulled from the target rather than `CHECK` failing.
Aside from checking the LogID is correct I'd like to also have the code to probe and determine which of the local entries differ from the target using the inclusion proof method I outlined elsewhere.  I've added #850 to track that.
