### ISSUE TITLE
[python] Monitor state file not found when log_id contains slash characters?

### ISSUE THREAD

**Issue by linshunghuang** [google/certificate-transparency#771]
When running python/utilities/logobserver/logobserver.py against Certly (or DigiCert, etc) log servers, it would fail like:
```
WARNING:root:Monitor state file not found, assuming first run.
ERROR:root:get-sth from https://log.certly.io failed: [Errno 2] No such file or directory: u'/tmp/ct_monitor/zbUXm3/BwEb+6jETaj+PAC5hgvr4iW/syLL1tatgSQA='
ERROR:root:Update failed
ERROR:root:Failed to update data for https://log.certly.io: latest timestamp is Wed Dec 31 16:00:00 1969
```
I'm guessing that this is because the monitor state files are named by the `log_id` but some IDs have slashes in them?

**Comment by pphaneuf** [comment]
Yeah, that's right, you can probably get it to work by running `mkdir -p /tmp/ct_monitor/zbUXm3/BwEb+6jETaj+PAC5hgvr4iW` first? But that's a bit of a hack...

We encountered this problem with `ct-server` as well, I think we ended up changing the encoding of the log IDs, to hex-encoding, I believe?

**Comment by linshunghuang** [comment]
Interesting hack :p Yeah, probably better to encode the log IDs.
