### ISSUE TITLE
CT doesn't build if OpenSSL is built with krb5 support

### ISSUE THREAD

**Issue by Martin2112** [google/certificate-transparency#875]
If OpenSSL is not built with OPENSSL_NO_KRB5 including openssl/ssl.h eventually includes krb5/krb5.h. This defines integer constants TRUE and FALSE as macros. 

These then prevent various .cc files compiling because they conflict with our enum definition of Status, which also tries to declare TRUE and FALSE.

This affects Fedora 22 using the system OpenSSL.

**Comment by pphaneuf** [comment]
Those are `enum`s that aren't `util::Status`, as I recall? I keep meaning to replace them with `util::Status` (possibly with the help of `StatusOr<>`, in many cases)...

**Comment by Martin2112** [comment]
Yes, the Cert class has a different status enum. Making it a c++11 enum might also fix this but a lot of unqualified references would need fixing up.

**Comment by Martin2112** [comment]
Hmmmm. That won't work though will it? The macros will still substitute numeric values and it won't compile.

**Comment by pphaneuf** [comment]
No, the macros are mean, and will reach through the nice `enum class` syntax... :cry: 

There's also things like this:

https://github.com/google/certificate-transparency/blob/master/cpp/util/json_wrapper.h#L7

**Comment by Martin2112** [comment]
I've looked at this more and getting rid of Cert::Status will improve readability quite a bit. e.g there are places that test for error by doing if (x != Cert::FALSE && x != Cert::TRUE). Using StatusOr will also remove some result pointer args.

It will also improve portability so I think I'll probably work on this.

**Comment by Martin2112** [comment]
I've reviewed deleting Cert::Status and I think it's too big a change to do in one step, both in terms of review size and the chance of introducing subtle bugs because of the required logic changes. I think it should be done in stages.

Files affected:

 cpp/client/async_log_client.cc
 cpp/client/ct.cc
 cpp/client/ssl_client.cc
 cpp/log/cert.cc
 cpp/log/cert.h
 cpp/log/cert_checker.cc
 cpp/log/cert_checker.h
 cpp/log/cert_checker_test.cc
 cpp/log/cert_submission_handler.cc
 cpp/log/cert_test.cc
 cpp/log/ct_extensions.cc
 cpp/log/ct_extensions_test.cc
 cpp/log/frontend_test.cc
 cpp/server/handler.cc

**Comment by pphaneuf** [comment]
I wholeheartedly embrace having many, many, many small changes that I can review easily. :smiley:

**Comment by Martin2112** [comment]
Now that Cert::Status has been removed the build process gets a bit farther. However Fedora is using GFlags 2.1, which appears to have changed namespace to gflags by default, though it is configurable via cmake.

**Comment by Martin2112** [comment]
Yay. That was the last hurdle. I now have it building on Fedora 22 and all the tests pass.
