### ISSUE TITLE
Test Flake: EtcdConsistentStoreTest.TestRejectsAddsWhenOverCapacity

### ISSUE THREAD

**Issue by Martin2112** [google/certificate-transparency#880]
Just saw this fail then pass when rerun. Log snippet follows.

```
[ RUN      ] EtcdConsistentStoreTest.TestRejectsAddsWhenOverCapacity cpp/log/etcd_consistent_store_test.cc:782: Failure
Value of: GetNumEtcdEntries()
  Actual: 201
Expected: 0
[  FAILED  ] EtcdConsistentStoreTest.TestRejectsAddsWhenOverCapacity (2002 ms)
[----------] 23 tests from EtcdConsistentStoreTest (6018 ms total)

[----------] Global test environment tear-down
[==========] 31 tests from 2 test cases ran. (6919 ms total)
[  PASSED  ] 30 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] EtcdConsistentStoreTest.TestRejectsAddsWhenOverCapacity
```

**Comment by Martin2112** [comment]
Exhibit B:

F1104 11:33:25.355763 10203 etcd_consistent_store_test.cc:579] Check failed: false 
*** Check failure stack trace: ***
F1104 11:33:25.355797 10202 etcd_consistent_store_test.cc:579] Check failed: false 
*** Check failure stack trace: ***
    @     0x7ff27c6d2dbd  google::LogMessage::Fail()
    @     0x7ff27c6d2dbd  google::LogMessage::Fail()
    @     0x7ff27c6d4c5d  google::LogMessage::SendToLog()
    @     0x7ff27c6d4c5d  google::LogMessage::SendToLog()
    @     0x7ff27c6d29ac  google::LogMessage::Flush()
    @     0x7ff27c6d29ac  google::LogMessage::Flush()
    @     0x7ff27c6d557e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff27c6d557e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff27df3af38  _ZNSt17_Function_handlerIFvRKN10cert_trans6UpdateIN2ct14SignedTreeHeadEEEEZNS0_44EtcdConsistentStoreTest_WatchServingSTH_Test8TestBodyEvEUlS6_E_E9_M_invokeERKSt9_Any_dataS6_
    @     0x7ff27df3af38  _ZNSt17_Function_handlerIFvRKN10cert_trans6UpdateIN2ct14SignedTreeHeadEEEEZNS0_44EtcdConsistentStoreTest_WatchServingSTH_Test8TestBodyEvEUlS6_E_E9_M_invokeERKSt9_Any_dataS6_
    @     0x7ff27df68d97  cert_trans::EtcdConsistentStore<>::ConvertSingleUpdate<>()
    @     0x7ff27df68cc2  cert_trans::EtcdConsistentStore<>::ConvertSingleUpdate<>()
    @     0x7ff27df7a315  cert_trans::FakeEtcdClient::RunWatchCallback()
    @     0x7ff27df7a315  cert_trans::FakeEtcdClient::RunWatchCallback()
    @     0x7ff27df944a1  cert_trans::ThreadPool::Impl::Worker()
    @     0x7ff27be1ba40  (unknown)
    @     0x7ff27df944a1  cert_trans::ThreadPool::Impl::Worker()
    @     0x7ff27be1ba40  (unknown)
    @     0x7ff27c291182  start_thread
    @     0x7ff27c291182  start_thread
    @     0x7ff27b79947d  (unknown)
    @     0x7ff27b79947d  (unknown)
Aborted (core dumped)

**Comment by Martin2112** [comment]
The CHECK failed because the test callback from store_->WatchServingSTH() was called three times and the test expected two.

**Comment by pphaneuf** [comment]
Not the real proble, but this ought to be a `ASSERT_LE(2, ...)`, for future generations.

**Comment by Martin2112** [comment]
In theory both of the flakes in this issue have now been fixed.
