### ISSUE TITLE
Default of --enable-hardening doesn't work on OSX

### ISSUE THREAD

**Issue by Martin2112** [google/certificate-transparency#959]
Not sure whether we should be turning this off automatically?

I'm seeing:

configure: error: could not find the OpenSSL libraries

From config.log:

configure:6354: g++ -o conftest -g -O2 -std=gnu++11 -fstack-protector-all -fPIE -Wa,--noexecstack -Wformat -Wformat-security -I../libevhtp-1.2.10 -I../libevhtp-1.2.10/evthr -I/usr/local/opt/openssl/include -I../libevhtp-1.2.10/htparse -D_FORTIFY_SOURCE=2 -L../libevhtp-1.2.10 -L/usr/local/opt/openssl/lib -pie -Wl,-z,relro,-z,now conftest.cpp -lssl   >&5
clang: warning: argument unused during compilation: '-pie'
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by benlaurie** [comment]
Looks to me like you only need some of it disabled, right?

Also, on OSX is might be better not to invoke clang via the gcc compatibility thingy...

**Comment by Martin2112** [comment]
That's probably true, but I haven't checked whether the remaining set of options are valid, or what impact there is on compatibility with the dependency library builds.

I wasn't aware of the gclient stuff, which might be a better way of solving these issues.

**Comment by AlCutter** [comment]
#958 solves this, at least partially (should build at least, though it might spit some warnings about unused flags.)

**Comment by Martin2112** [comment]
I think we can close this as it does now build correctly with gclient.
