### ISSUE TITLE
CT information not updated in the lock icon even after SCT is received as shown in chrome://net-internals

### ISSUE THREAD

**Issue by AnimeshChhotaray** [google/certificate-transparency#990]
I observed this on 2 sites: drive.google.com and gmail.com
![ct1](https://cloud.githubusercontent.com/assets/15241422/10657448/a98e7bde-7859-11e5-8874-b9c408bf1c11.png)

**Comment by eranmes** [comment]
Could you capture and attach the net-log of such a session?

**Comment by AnimeshChhotaray** [comment]
Hey Eran,
PFA the net-log for gmail.
I could not reproduce for google drive.

On Fri, Oct 23, 2015 at 8:53 AM, Eran Messeri <notifications@github.com>
wrote:

> Could you capture and attach the net-log of such a session?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/certificate-transparency/issues/990#issuecomment-150562555>
> .
>



-- 

Thanks,
Animesh Chhotaray
Department of Computer and Information Sciences & Engg.
University of Florida

**Comment by eranmes** [comment]
I think GitHub dropped your attachment when you emailed it, as I can't find it.
Please re-attach.
The screenshots are a bit misleading as they are titled with different domains than the ones seen in the origin information bubble.
One suspect is QUIC - we don't yet support CT in QUIC connections established by Chrome, which is what Chrome uses for connections  to Google. To tell if that was used I'd need the netlog.

**Comment by AnimeshChhotaray** [comment]
[net-internal-log.json.txt](https://github.com/google/certificate-transparency/files/34666/net-internal-log.json.txt)
